enable-module-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

patches-version = "v4.3.0-dev.4"
cli-source = "MorpheApp/morphe-cli"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

#Stock Icon

[AnddeaYouTubeRVXAPK]
archive-dlurl = "https://archive.org/download/thh-apks/yt"
patches-source = "anddea/revanced-patches"
rv-brand = "anddea Morphe"
build-mode = "apk"
version = "20.51.39"
included-patches = "'MaterialYou'"
patcher-args = "-e 'Custom branding icon for YouTube' -e 'Custom header for YouTube' -e 'GmsCore support' -OpackageNameYouTube=app.revanced.android.youtube "

[AnddeaYouTubeRVXModule]
archive-dlurl = "https://archive.org/download/thh-apks/yt"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea Morphe"
build-mode = "module"
version = "20.51.39"
included-patches = "'MaterialYou'"

[AnddeaYouTubeMusicRVXAPK]

archive-dlurl = "https://archive.org/download/thh-apks/ytm"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea Morphe"
arch = "both"
build-mode = "apk"
version = "9.15.51"
patcher-args = "-e 'Custom branding icon for YouTube Music' -e 'Custom header for YouTube Music' -e 'GmsCore support' -OpackageNameYouTubeMusic=app.revanced.android.apps.youtube.music "

[AnddeaYouTubeMusicRVXModule]

archive-dlurl = "https://archive.org/download/thh-apks/ytm"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea Morphe"
arch = "both"
build-mode = "module"
version = "9.15.51"
patcher-args = "-e 'Custom branding icon for YouTube Music' -e 'Custom header for YouTube Music' "




